/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VpsMonitorRouteImport } from './routes/vps-monitor'
import { Route as VpsControlRouteImport } from './routes/vps-control'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as ServerControlRouteImport } from './routes/server-control'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'

const VpsMonitorRoute = VpsMonitorRouteImport.update({
  id: '/vps-monitor',
  path: '/vps-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const VpsControlRoute = VpsControlRouteImport.update({
  id: '/vps-control',
  path: '/vps-control',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerControlRoute = ServerControlRouteImport.update({
  id: '/server-control',
  path: '/server-control',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/monitor': typeof MonitorRoute
  '/queue': typeof QueueRoute
  '/server-control': typeof ServerControlRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/vps-control': typeof VpsControlRoute
  '/vps-monitor': typeof VpsMonitorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/monitor': typeof MonitorRoute
  '/queue': typeof QueueRoute
  '/server-control': typeof ServerControlRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/vps-control': typeof VpsControlRoute
  '/vps-monitor': typeof VpsMonitorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/monitor': typeof MonitorRoute
  '/queue': typeof QueueRoute
  '/server-control': typeof ServerControlRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/vps-control': typeof VpsControlRoute
  '/vps-monitor': typeof VpsMonitorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/history'
    | '/logs'
    | '/monitor'
    | '/queue'
    | '/server-control'
    | '/servers'
    | '/settings'
    | '/vps-control'
    | '/vps-monitor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/history'
    | '/logs'
    | '/monitor'
    | '/queue'
    | '/server-control'
    | '/servers'
    | '/settings'
    | '/vps-control'
    | '/vps-monitor'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/history'
    | '/logs'
    | '/monitor'
    | '/queue'
    | '/server-control'
    | '/servers'
    | '/settings'
    | '/vps-control'
    | '/vps-monitor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  HistoryRoute: typeof HistoryRoute
  LogsRoute: typeof LogsRoute
  MonitorRoute: typeof MonitorRoute
  QueueRoute: typeof QueueRoute
  ServerControlRoute: typeof ServerControlRoute
  ServersRoute: typeof ServersRoute
  SettingsRoute: typeof SettingsRoute
  VpsControlRoute: typeof VpsControlRoute
  VpsMonitorRoute: typeof VpsMonitorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vps-monitor': {
      id: '/vps-monitor'
      path: '/vps-monitor'
      fullPath: '/vps-monitor'
      preLoaderRoute: typeof VpsMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vps-control': {
      id: '/vps-control'
      path: '/vps-control'
      fullPath: '/vps-control'
      preLoaderRoute: typeof VpsControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-control': {
      id: '/server-control'
      path: '/server-control'
      fullPath: '/server-control'
      preLoaderRoute: typeof ServerControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  HistoryRoute: HistoryRoute,
  LogsRoute: LogsRoute,
  MonitorRoute: MonitorRoute,
  QueueRoute: QueueRoute,
  ServerControlRoute: ServerControlRoute,
  ServersRoute: ServersRoute,
  SettingsRoute: SettingsRoute,
  VpsControlRoute: VpsControlRoute,
  VpsMonitorRoute: VpsMonitorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
